import { Heading, Text } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Container } from '../components/Container'

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Hello World</title>
        <meta name="description" content="Generated by Futhememe boilerplate generator" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading fontSize='7xl'>HELLO WORLD</Heading>
      <Text>Project generated with ❤️ by Futhememe boilerplate generator</Text>
    </Container>
  )
}

export default Home
